<template>
  <video
    crossorigin="anonymous"
    playsinline
    poster="../video/poster.png"
    src="https://static.sollenaturals.com/files/3ce66cfb-e88a-4757-b103-de9a0936253d/Solle_Naturals_trial-pack-landing.mp4"
    muted
    loop
    autoplay
    preload="metadata"
  />
</template>
