<template>
  <video
    crossorigin="anonymous"
    playsinline
    poster="../video/poster.png"
    src="https://sollefiles.s3.us-east-005.backblazeb2.com/files/1c6bc5e1-32ac-4d6c-aee1-fb70c7f380a9/Solle_Naturals_trial-pack-landing-mobile.mp4"
    muted
    loop
    autoplay
    preload="metadata"
  />
</template>
