name: Build and Deploy - DEV

on:
  push:
    branches: ['dev']

env:
  NODE_ENV: development
  PORT: 8080
  VUE_APP_CHECKOUT_URL: ${{ vars.DEV_CHECKOUT_URL }}
  VUE_APP_NAME: "3 Day Reset Trial box"

jobs:
  checkout-build-auth-deploy:
    name: 'Checkout and Deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'checkout'
        uses: actions/checkout@v3
        
      - id: 'npm-install'
        run: npm install

      - id: 'npm-build'
        run: npm run build

      - id: 'auth-with-gcp'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.DEV_GCP_SA_KEY }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v2'
        with:
          project_id: solle-web-dev
          deliverables: app.yaml
          build_env_vars: |-
            NODE_ENV=development
            PORT=8080
            VUE_APP_CHECKOUT_URL=${{ vars.DEV_CHECKOUT_URL }}
            VUE_APP_NAME="3 Day Reset Trial box"
          env_vars: |-
            NODE_ENV=development
            PORT=8080
            VUE_APP_CHECKOUT_URL=${{ vars.DEV_CHECKOUT_URL }}
            VUE_APP_NAME="3 Day Reset Trial box"
